name: Deploy Hexo to GitHub Pages

on:
  push:
    branches:
      - master # 你的主分支名，如果是main请改成main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true # 确保拉取主题文件

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20 # 用你本地一致的Node版本

      - name: Install dependencies
        run: |
          npm install -g hexo-cli
          npm install

      - name: Build Hexo site
        run: hexo clean && hexo generate

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public # Hexo生成的静态文件目录